# Generated by Django 4.1 on 2022-09-11 21:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('direction', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='debit', max_length=10)),
                ('schedule', models.DateField(default=datetime.date(2022, 9, 12))),
                ('result', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'fail')], default='pending', max_length=10)),
                ('dst_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detinations', to='api.bankaccount')),
                ('src_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='api.bankaccount')),
            ],
        ),
    ]
