# Generated by Django 4.1 on 2022-09-14 13:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('direction', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='debit', max_length=10)),
                ('result', models.CharField(blank=True, choices=[('success', 'success'), ('fail', 'fail')], max_length=10, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('dst_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detinations', to='api.bankaccount')),
                ('src_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='api.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessScheduledTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateField(default=datetime.date.today)),
                ('amount', models.FloatField()),
                ('direction', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='debit', max_length=10)),
                ('success', models.IntegerField(default=0)),
                ('fail_once', models.IntegerField(default=0)),
                ('fail_completely', models.IntegerField(default=0)),
                ('dates_done', models.IntegerField(default=0)),
                ('credit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transaction')),
                ('dst_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_detinations', to='api.bankaccount')),
                ('src_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sources', to='api.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='FailScheduledTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
        ),
    ]
