# Generated by Django 4.1 on 2022-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtransaction',
            name='dates_done',
            field=models.IntegerField(default=0),
        ),
    ]
