# Generated by Django 4.1 on 2022-09-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledtransaction',
            old_name='succes',
            new_name='success',
        ),
    ]
