# Generated by Django 4.1 on 2022-09-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtransaction',
            name='token',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
