# Generated by Django 4.1 on 2022-09-12 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='scheduledtransaction',
            name='started_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
